from collections import namedtuple

CountryVAT = namedtuple('CountryVAT', ('name', 'id', 'navision_customer', 'navision_department', 'navision_vat_account_number', 'navision_vat_business_posting_group'))

vat_dicts = {
    'AF' : CountryVAT('Afghanistan', 'AF', 'WAF', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'AX' : CountryVAT('Åland Islands', 'AX', 'WAX', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'AL' : CountryVAT('Albania', 'AL', 'WAL', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'DZ' : CountryVAT('Algeria', 'DZ', 'WDZ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'AS' : CountryVAT('American Samoa', 'AS', 'WAS', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'AD' : CountryVAT('Andorra', 'AD', 'WAD', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'AO' : CountryVAT('Angola', 'AO', 'WAO', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'AI' : CountryVAT('Anguilla', 'AI', 'WAI', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'AQ' : CountryVAT('Antarctica', 'AQ', 'WAQ', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'AG' : CountryVAT('Antigua and Barbuda', 'AG', 'WAG', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'AR' : CountryVAT('Argentina', 'AR', 'WAR', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'AM' : CountryVAT('Armenia', 'AM', 'WAM', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'AW' : CountryVAT('Aruba', 'AW', 'WAW', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'AC' : CountryVAT('Ascension Island', 'AC', 'WAC', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'AU' : CountryVAT('Australia', 'AU', 'WAU', 'PROFIT-WEB ASIA', '25165', 'AUWEB'),
    'AT' : CountryVAT('Austria', 'AT', 'WAT', 'PROFIT-WEB EMEA', '25165', 'AT'),
    'AZ' : CountryVAT('Azerbaijan', 'AZ', 'WAZ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BS' : CountryVAT('Bahamas', 'BS', 'WBS', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'BH' : CountryVAT('Bahrain', 'BH', 'WBH', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BD' : CountryVAT('Bangladesh', 'BD', 'WBD', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'BB' : CountryVAT('Barbados', 'BB', 'WBB', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'BY' : CountryVAT('Belarus', 'BY', 'WBY', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BE' : CountryVAT('Belgium', 'BE', 'WBE', 'PROFIT-WEB EMEA', '25165', 'BE'),
    'BZ' : CountryVAT('Belize', 'BZ', 'WBZ', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'BJ' : CountryVAT('Benin', 'BJ', 'WBJ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BM' : CountryVAT('Bermuda', 'BM', 'WBM', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'BT' : CountryVAT('Bhutan', 'BT', 'WBT', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'BO' : CountryVAT('Bolivia', 'BO', 'WBO', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'BA' : CountryVAT('Bosnia and Herzegovina', 'BA', 'WBA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BW' : CountryVAT('Botswana', 'BW', 'WBW', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BV' : CountryVAT('Bouvet Island', 'BV', 'WBV', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'BR' : CountryVAT('Brazil', 'BR', 'WBR', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'IO' : CountryVAT('British Indian Ocean Territory', 'IO', 'WIO', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'VG' : CountryVAT('British Virgin Islands', 'VG', 'WVG', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'BN' : CountryVAT('Brunei', 'BN', 'WBN', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'BG' : CountryVAT('Bulgaria', 'BG', 'WBG', 'PROFIT-WEB EMEA', '25165', 'BG'),
    'BF' : CountryVAT('Burkina Faso', 'BF', 'WBF', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BI' : CountryVAT('Burundi', 'BI', 'WBI', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'KH' : CountryVAT('Cambodia', 'KH', 'WKH', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'CM' : CountryVAT('Cameroon', 'CM', 'WCM', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'CA' : CountryVAT('Canada', 'CA', 'WCA', 'PROFIT-WEB AMERICAS', '25165', 'GSTWEB'),
    'IC' : CountryVAT('Canary Islands', 'IC', 'WIC', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'CV' : CountryVAT('Cape Verde', 'CV', 'WCV', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BQ' : CountryVAT('Caribbean Netherlands', 'BQ', 'WBQ', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'KY' : CountryVAT('Cayman Islands', 'KY', 'WKY', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'CF' : CountryVAT('Central African Republic', 'CF', 'WCF', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'EA' : CountryVAT('Ceuta and Melilla', 'EA', 'WEA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'TD' : CountryVAT('Chad', 'TD', 'WTD', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'CL' : CountryVAT('Chile', 'CL', 'WCL', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'CN' : CountryVAT('China', 'CN', 'WCN', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'CX' : CountryVAT('Christmas Island', 'CX', 'WCX', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'CP' : CountryVAT('Clipperton Island', 'CP', 'WCP', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'CC' : CountryVAT('Cocos (Keeling) Islands', 'CC', 'WCC', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'CO' : CountryVAT('Colombia', 'CO', 'WCO', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'KM' : CountryVAT('Comoros', 'KM', 'WKM', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'CG' : CountryVAT('Congo - Brazzaville', 'CG', 'WCG', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'CD' : CountryVAT('Congo - Kinshasa', 'CD', 'WCD', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'CK' : CountryVAT('Cook Islands', 'CK', 'WCK', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'CR' : CountryVAT('Costa Rica', 'CR', 'WCR', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'CI' : CountryVAT('Côte d’Ivoire', 'CI', 'WCI', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'HR' : CountryVAT('Croatia', 'HR', 'WHR', 'PROFIT-WEB EMEA', '25165', 'HR'),
    'CU' : CountryVAT('Cuba', 'CU', 'WCU', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'CW' : CountryVAT('Curaçao', 'CW', 'WCW', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'CY' : CountryVAT('Cyprus', 'CY', 'WCY', 'PROFIT-WEB EMEA', '25165', 'CY'),
    'CZ' : CountryVAT('Czech Republic', 'CZ', 'WCZ', 'PROFIT-WEB EMEA', '25165', 'CZ'),
    'DK' : CountryVAT('Denmark', 'DK', 'WDK', 'PROFIT-WEB EMEA', '25165', 'IND./WEB'),
    'DG' : CountryVAT('Diego Garcia', 'DG', 'WDG', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'DJ' : CountryVAT('Djibouti', 'DJ', 'WDJ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'DM' : CountryVAT('Dominica', 'DM', 'WDM', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'DO' : CountryVAT('Dominican Republic', 'DO', 'WDO', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'EC' : CountryVAT('Ecuador', 'EC', 'WEC', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'EG' : CountryVAT('Egypt', 'EG', 'WEG', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SV' : CountryVAT('El Salvador', 'SV', 'WSV', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'GQ' : CountryVAT('Equatorial Guinea', 'GQ', 'WGQ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'ER' : CountryVAT('Eritrea', 'ER', 'WER', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'EE' : CountryVAT('Estonia', 'EE', 'WEE', 'PROFIT-WEB EMEA', '25165', 'EE'),
    'ET' : CountryVAT('Ethiopia', 'ET', 'WET', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'FK' : CountryVAT('Falkland Islands', 'FK', 'WFK', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'FO' : CountryVAT('Faroe Islands', 'FO', 'WFO', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'FJ' : CountryVAT('Fiji', 'FJ', 'WFJ', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'FI' : CountryVAT('Finland', 'FI', 'WFI', 'PROFIT-WEB EMEA', '25165', 'FI'),
    'FR' : CountryVAT('France', 'FR', 'WFR', 'PROFIT-WEB EMEA', '25165', 'FR'),
    'GF' : CountryVAT('French Guiana', 'GF', 'WGF', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'PF' : CountryVAT('French Polynesia', 'PF', 'WPF', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TF' : CountryVAT('French Southern Territories', 'TF', 'WTF', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'GA' : CountryVAT('Gabon', 'GA', 'WGA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GM' : CountryVAT('Gambia', 'GM', 'WGM', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GE' : CountryVAT('Georgia', 'GE', 'WGE', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'DE' : CountryVAT('Germany', 'DE', 'WDE', 'PROFIT-WEB EMEA', '25165', 'DE'),
    'GH' : CountryVAT('Ghana', 'GH', 'WGH', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GI' : CountryVAT('Gibraltar', 'GI', 'WGI', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GR' : CountryVAT('Greece', 'GR', 'WGR', 'PROFIT-WEB EMEA', '25165', 'GR'),
    'GL' : CountryVAT('Greenland', 'GL', 'WGL', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'GD' : CountryVAT('Grenada', 'GD', 'WGD', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'GP' : CountryVAT('Guadeloupe', 'GP', 'WGP', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GU' : CountryVAT('Guam', 'GU', 'WGU', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'GT' : CountryVAT('Guatemala', 'GT', 'WGT', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GG' : CountryVAT('Guernsey', 'GG', 'WGG', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GN' : CountryVAT('Guinea', 'GN', 'WGN', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GW' : CountryVAT('Guinea-Bissau', 'GW', 'WGW', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GY' : CountryVAT('Guyana', 'GY', 'WGY', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'HT' : CountryVAT('Haiti', 'HT', 'WHT', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'HM' : CountryVAT('Heard & McDonald Islands', 'HM', 'WHM', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'HN' : CountryVAT('Honduras', 'HN', 'WHN', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'HK' : CountryVAT('Hong Kong SAR China', 'HK', 'WHK', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'HU' : CountryVAT('Hungary', 'HU', 'WHU', 'PROFIT-WEB EMEA', '25165', 'HU'),
    'IS' : CountryVAT('Iceland', 'IS', 'WIS', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'IN' : CountryVAT('India', 'IN', 'WIN', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'ID' : CountryVAT('Indonesia', 'ID', 'WID', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'IR' : CountryVAT('Iran', 'IR', 'WIR', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'IQ' : CountryVAT('Iraq', 'IQ', 'WIQ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'IE' : CountryVAT('Ireland', 'IE', 'WIE', 'PROFIT-WEB EMEA', '25165', 'IE'),
    'IM' : CountryVAT('Isle of Man', 'IM', 'WIM', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'IL' : CountryVAT('Israel', 'IL', 'WIL', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'IT' : CountryVAT('Italy', 'IT', 'WIT', 'PROFIT-WEB EMEA', '25165', 'IT'),
    'JM' : CountryVAT('Jamaica', 'JM', 'WJM', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'JP' : CountryVAT('Japan', 'JP', 'WJP', 'PROFIT-WEB ASIA', '25165', 'JP'),
    'JE' : CountryVAT('Jersey', 'JE', 'WJE', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'JO' : CountryVAT('Jordan', 'JO', 'WJO', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'KZ' : CountryVAT('Kazakhstan', 'KZ', 'WKZ', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'KE' : CountryVAT('Kenya', 'KE', 'WKE', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'KI' : CountryVAT('Kiribati', 'KI', 'WKI', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'XK' : CountryVAT('Kosovo', 'XK', 'WXK', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'KW' : CountryVAT('Kuwait', 'KW', 'WKW', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'KG' : CountryVAT('Kyrgyzstan', 'KG', 'WKG', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'LA' : CountryVAT('Laos', 'LA', 'WLA', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'LV' : CountryVAT('Latvia', 'LV', 'WLV', 'PROFIT-WEB EMEA', '25165', 'LV'),
    'LB' : CountryVAT('Lebanon', 'LB', 'WLB', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'LS' : CountryVAT('Lesotho', 'LS', 'WLS', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'LR' : CountryVAT('Liberia', 'LR', 'WLR', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'LY' : CountryVAT('Libya', 'LY', 'WLY', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'LI' : CountryVAT('Liechtenstein', 'LI', 'WLI', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'LT' : CountryVAT('Lithuania', 'LT', 'WLT', 'PROFIT-WEB EMEA', '25165', 'LT'),
    'LU' : CountryVAT('Luxembourg', 'LU', 'WLU', 'PROFIT-WEB EMEA', '25165', 'LU'),
    'MO' : CountryVAT('Macau SAR China', 'MO', 'WMO', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'MK' : CountryVAT('Macedonia', 'MK', 'WMK', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MG' : CountryVAT('Madagascar', 'MG', 'WMG', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MW' : CountryVAT('Malawi', 'MW', 'WMW', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MY' : CountryVAT('Malaysia', 'MY', 'WMY', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'MV' : CountryVAT('Maldives', 'MV', 'WMV', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'ML' : CountryVAT('Mali', 'ML', 'WML', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MT' : CountryVAT('Malta', 'MT', 'WMT', 'PROFIT-WEB EMEA', '25165', 'MT'),
    'MH' : CountryVAT('Marshall Islands', 'MH', 'WMH', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'MQ' : CountryVAT('Martinique', 'MQ', 'WMQ', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'MR' : CountryVAT('Mauritania', 'MR', 'WMR', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MU' : CountryVAT('Mauritius', 'MU', 'WMU', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'YT' : CountryVAT('Mayotte', 'YT', 'WYT', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MX' : CountryVAT('Mexico', 'MX', 'WMX', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'FM' : CountryVAT('Micronesia', 'FM', 'WFM', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'MD' : CountryVAT('Moldova', 'MD', 'WMD', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MC' : CountryVAT('Monaco', 'MC', 'WMC', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MN' : CountryVAT('Mongolia', 'MN', 'WMN', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'ME' : CountryVAT('Montenegro', 'ME', 'WME', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MS' : CountryVAT('Montserrat', 'MS', 'WMS', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'MA' : CountryVAT('Morocco', 'MA', 'WMA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MZ' : CountryVAT('Mozambique', 'MZ', 'WMZ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'MM' : CountryVAT('Myanmar (Burma)', 'MM', 'WMM', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'NA' : CountryVAT('Namibia', 'NA', 'WNA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'NR' : CountryVAT('Nauru', 'NR', 'WNR', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'NP' : CountryVAT('Nepal', 'NP', 'WNP', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'NL' : CountryVAT('Netherlands', 'NL', 'WNL', 'PROFIT-WEB EMEA', '25165', 'NL'),
    'NC' : CountryVAT('New Caledonia', 'NC', 'WNC', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'NZ' : CountryVAT('New Zealand', 'NZ', 'WNZ', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'NI' : CountryVAT('Nicaragua', 'NI', 'WNI', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'NE' : CountryVAT('Niger', 'NE', 'WNE', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'NG' : CountryVAT('Nigeria', 'NG', 'WNG', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'NU' : CountryVAT('Niue', 'NU', 'WNU', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'NF' : CountryVAT('Norfolk Island', 'NF', 'WNF', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'MP' : CountryVAT('Northern Mariana Islands', 'MP', 'WMP', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'KP' : CountryVAT('North Korea', 'KP', 'WKP', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'NO' : CountryVAT('Norway', 'NO', 'WNO', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'OM' : CountryVAT('Oman', 'OM', 'WOM', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'PK' : CountryVAT('Pakistan', 'PK', 'WPK', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'PW' : CountryVAT('Palau', 'PW', 'WPW', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'PS' : CountryVAT('Palestinian Territories', 'PS', 'WPS', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'PA' : CountryVAT('Panama', 'PA', 'WPA', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'PG' : CountryVAT('Papua New Guinea', 'PG', 'WPG', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'PY' : CountryVAT('Paraguay', 'PY', 'WPY', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'PE' : CountryVAT('Peru', 'PE', 'WPE', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'PH' : CountryVAT('Philippines', 'PH', 'WPH', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'PN' : CountryVAT('Pitcairn Islands', 'PN', 'WPN', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'PL' : CountryVAT('Poland', 'PL', 'WPL', 'PROFIT-WEB EMEA', '25165', 'PL'),
    'PT' : CountryVAT('Portugal', 'PT', 'WPT', 'PROFIT-WEB EMEA', '25165', 'PT'),
    'PR' : CountryVAT('Puerto Rico', 'PR', 'WPR', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'QA' : CountryVAT('Qatar', 'QA', 'WQA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'RE' : CountryVAT('Réunion', 'RE', 'WRE', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'RO' : CountryVAT('Romania', 'RO', 'WRO', 'PROFIT-WEB EMEA', '25165', 'RO'),
    'RU' : CountryVAT('Russia', 'RU', 'WRU', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'RW' : CountryVAT('Rwanda', 'RW', 'WRW', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'BL' : CountryVAT('Saint Barthélemy', 'BL', 'WBL', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'SH' : CountryVAT('Saint Helena', 'SH', 'WSH', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'KN' : CountryVAT('Saint Kitts and Nevis', 'KN', 'WKN', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'LC' : CountryVAT('Saint Lucia', 'LC', 'WLC', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'MF' : CountryVAT('Saint Martin', 'MF', 'WMF', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'PM' : CountryVAT('Saint Pierre and Miquelon', 'PM', 'WPM', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'WS' : CountryVAT('Samoa', 'WS', 'WWS', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'SM' : CountryVAT('San Marino', 'SM', 'WSM', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'ST' : CountryVAT('São Tomé and Príncipe', 'ST', 'WST', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SA' : CountryVAT('Saudi Arabia', 'SA', 'WSA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SN' : CountryVAT('Senegal', 'SN', 'WSN', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'RS' : CountryVAT('Serbia', 'RS', 'WRS', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SC' : CountryVAT('Seychelles', 'SC', 'WSC', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SL' : CountryVAT('Sierra Leone', 'SL', 'WSL', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SG' : CountryVAT('Singapore', 'SG', 'WSG', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'SX' : CountryVAT('Sint Maarten', 'SX', 'WSX', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'SK' : CountryVAT('Slovakia', 'SK', 'WSK', 'PROFIT-WEB EMEA', '25165', 'SK'),
    'SI' : CountryVAT('Slovenia', 'SI', 'WSI', 'PROFIT-WEB EMEA', '25165', 'SI'),
    'SB' : CountryVAT('Solomon Islands', 'SB', 'WSB', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'SO' : CountryVAT('Somalia', 'SO', 'WSO', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'ZA' : CountryVAT('South Africa', 'ZA', 'WZA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GS' : CountryVAT('South Georgia & South Sandwich Islands', 'GS', 'WGS', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'KR' : CountryVAT('South Korea', 'KR', 'WKR', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'SS' : CountryVAT('South Sudan', 'SS', 'WSS', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'ES' : CountryVAT('Spain', 'ES', 'WES', 'PROFIT-WEB EMEA', '25165', 'ES'),
    'LK' : CountryVAT('Sri Lanka', 'LK', 'WLK', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'VC' : CountryVAT('St. Vincent & Grenadines', 'VC', 'WVC', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'SD' : CountryVAT('Sudan', 'SD', 'WSD', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SR' : CountryVAT('Suriname', 'SR', 'WSR', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'SJ' : CountryVAT('Svalbard and Jan Mayen', 'SJ', 'WSJ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SZ' : CountryVAT('Swaziland', 'SZ', 'WSZ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SE' : CountryVAT('Sweden', 'SE', 'WSE', 'PROFIT-WEB EMEA', '25165', 'SE'),
    'CH' : CountryVAT('Switzerland', 'CH', 'WCH', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'SY' : CountryVAT('Syria', 'SY', 'WSY', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'TW' : CountryVAT('Taiwan', 'TW', 'WTW', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TJ' : CountryVAT('Tajikistan', 'TJ', 'WTJ', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TZ' : CountryVAT('Tanzania', 'TZ', 'WTZ', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'TH' : CountryVAT('Thailand', 'TH', 'WTH', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TL' : CountryVAT('Timor-Leste', 'TL', 'WTL', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TG' : CountryVAT('Togo', 'TG', 'WTG', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'TK' : CountryVAT('Tokelau', 'TK', 'WTK', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TO' : CountryVAT('Tonga', 'TO', 'WTO', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TT' : CountryVAT('Trinidad and Tobago', 'TT', 'WTT', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'TA' : CountryVAT('Tristan da Cunha', 'TA', 'WTA', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TN' : CountryVAT('Tunisia', 'TN', 'WTN', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'TR' : CountryVAT('Turkey', 'TR', 'WTR', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'TM' : CountryVAT('Turkmenistan', 'TM', 'WTM', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'TC' : CountryVAT('Turks and Caicos Islands', 'TC', 'WTC', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'TV' : CountryVAT('Tuvalu', 'TV', 'WTV', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'UG' : CountryVAT('Uganda', 'UG', 'WUG', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'UA' : CountryVAT('Ukraine', 'UA', 'WUA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'AE' : CountryVAT('United Arab Emirates', 'AE', 'WAE', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'GB' : CountryVAT('United Kingdom', 'GB', 'WGB', 'PROFIT-WEB EMEA', '25165', 'GB'),
    'US' : CountryVAT('United States', 'US', 'WUS', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'UY' : CountryVAT('Uruguay', 'UY', 'WUY', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'UM' : CountryVAT('U.S. Outlying Islands', 'UM', 'WUM', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'VI' : CountryVAT('U.S. Virgin Islands', 'VI', 'WVI', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'UZ' : CountryVAT('Uzbekistan', 'UZ', 'WUZ', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'VU' : CountryVAT('Vanuatu', 'VU', 'WVU', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'VA' : CountryVAT('Vatican City', 'VA', 'WVA', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'VE' : CountryVAT('Venezuela', 'VE', 'WVE', 'PROFIT-WEB AMERICAS', '25165', 'UDL./WEB'),
    'VN' : CountryVAT('Vietnam', 'VN', 'WVN', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'WF' : CountryVAT('Wallis and Futuna', 'WF', 'WWF', 'PROFIT-WEB ASIA', '25165', 'UDL./WEB'),
    'EH' : CountryVAT('Western Sahara', 'EH', 'WEH', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'YE' : CountryVAT('Yemen', 'YE', 'WYE', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'ZM' : CountryVAT('Zambia', 'ZM', 'WZM', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
    'ZW' : CountryVAT('Zimbabwe', 'ZW', 'WZW', 'PROFIT-WEB EMEA', '25165', 'UDL./WEB'),
}